GET http://localhost:5033/games

###

// getGameById
GET http://localhost:5033/games/9

###

// createGame
POST http://localhost:5033/games
Content-Type: application/json

{
    "name": "Super Mario BangBros",
    "genre": "Adventure",
    "price": 699.99,
    "releaseDate": "2024-07-15"
}

###

// updateGame
PUT http://localhost:5033/games/9
Content-Type: application/json

{
    "name": "Super Mario",
    "genre": "Arcade",
    "price": 9.99,
    "releaseDate": "2026-01-01"
}

###

// deleteGame
DELETE http://localhost:5033/games/9